# Numpy

-  Numeric Python
-  Scikit learn library uses Numpy as backhand
-  Used for 1D and 2D processing at a faster time

In [1]:
import numpy as np

## Numpy Array

In [2]:
#One Dimensonal Matrix

vec = [1,2,3,4] #Simple list has to be converted to array

In [3]:
np_vec = np.array(vec)

In [4]:
np_vec

array([1, 2, 3, 4])

In [5]:
type(np_vec)

numpy.ndarray

In [ ]:
#Arithmetic Operations can't be done in Lists, whereas array can do it.

In [10]:
a = [1,2,3] 
b = [3,4,5]
print(a+b)

[1, 2, 3, 3, 4, 5]


In [11]:
a1 = np.array(a)

b1 = np.array(b)

print(a1+b1)

[4 6 8]


In [13]:
#Two Dimensional Array

In [14]:
mat = [a,b]

In [15]:
mat

[[1, 2, 3], [3, 4, 5]]

In [16]:
mat1 = np.array(mat)

In [17]:
mat1

array([[1, 2, 3],
       [3, 4, 5]])

## Zeros,Ones, Eye

In [18]:
np.zeros((3,4)) #Rows X Columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.eye(3) #It creates 3X3 matrix where diagonal makes value

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random

In [21]:
np.random.randn(5) #creates 5 random value in 1D 

array([ 1.80267685, -0.04505137, -1.30718341, -0.88834667,  1.4859307 ])

In [22]:
np.random.randn(3,4) #creates 3X4 random value matrix

array([[ 0.751114  , -1.041507  , -1.10415783, -0.72298678],
       [ 1.0896793 ,  0.73296797,  0.06322308, -1.08657226],
       [ 1.43619007, -1.43084673,  1.58245623,  0.78882087]])

In [23]:
np.random.randint(10,20,6) #start,stop,random numbers to be generated

array([16, 18, 10, 12, 18, 15])

## Arange, Linspace

In [24]:
np.arange(2,21,2) #start,stop,step. Note: last element would be negelcted

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [25]:
np.linspace(2,5,num=10) #By default it generates num=50 evenly spaced values and endpoint is true(included)

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [26]:
np_vec

array([1, 2, 3, 4])

In [27]:
mat1

array([[1, 2, 3],
       [3, 4, 5]])

In [29]:
np_vec.shape #To view the shape of matrix

(4,)

In [31]:
mat1.max() #To find max value

5

In [33]:
mat1.reshape(3,2) #note: reshaping matrix should match with orignal

array([[1, 2],
       [3, 3],
       [4, 5]])

In [34]:
mat1.dtype #outputs data type 

dtype('int32')