## Numpy Operations

In [1]:
import numpy as np

In [2]:
a = np.array([2,3,4,5])

In [3]:
a + 7

array([ 9, 10, 11, 12])

In [4]:
a - 2

array([0, 1, 2, 3])

In [5]:
a *3 

array([ 6,  9, 12, 15])

In [6]:
a/2

array([1. , 1.5, 2. , 2.5])

In [7]:
np.cos(a)

array([-0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [9]:
np.sum(a) #sum of all values

14

In [10]:
np.median(a)

3.5

In [12]:
a1 = np.array(([1,3],[2,3]))
b1 = np.array(([1,2],[2,3]))

In [13]:
a1*b1 #normal multiplication

array([[1, 6],
       [4, 9]])

In [14]:
a1.dot(b1) #matrix multiplication

array([[ 7, 11],
       [ 8, 13]])

In [15]:
a

array([2, 3, 4, 5])

In [16]:
a > 4

array([False, False, False,  True])