In [1]:
import numpy as np

In [2]:
d1 = np.arange(25) #creates 25 values 1D matrix

In [3]:
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [6]:
d2 = np.arange(25).reshape(5,5) #creates 25 values in 5X5 matrix

In [5]:
d2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### Indexing format

-  start:end+1

Note: end point isn't included in index by default. So add 1 index value to include end point

In [7]:
d1[0:4] #4th index not included

array([0, 1, 2, 3])

In [8]:
d1[:7] #get matrix value from starting to 6th index

array([0, 1, 2, 3, 4, 5, 6])

In [9]:
d1[3:]#get matrix value from 3rd index to last

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24])

In [12]:
d1[3::-1] #Getting Reverse values  

array([3, 2, 1, 0])

In [14]:
d1[12:3:-2]

array([12, 10,  8,  6,  4])

In [20]:
d1[-8:-1]

array([17, 18, 19, 20, 21, 22, 23])

In [21]:
d2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
d2[1,2] #d2[rows,colums]

7

In [28]:
d2[2,:] #to select a particular row

array([10, 11, 12, 13, 14])

In [29]:
d2[2:] #Without coma, it will select all rows n columns after 2nd index

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
d2[:,3]

array([ 3,  8, 13, 18, 23])

In [31]:
d2[1:4,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [32]:
d2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
d2[0:,2:4]

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18],
       [22, 23]])

### Broadcasting

In [35]:
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
d1[0:2] = -2 #replaces value from 0th and 1st index as -2

In [37]:
d1

array([-2, -2,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])